runtime: nodejs10
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always
  - url: /.*
    script: auto
    secure: always
env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  BASE_URL: "https://www.hansdesmet.be"
  CANONICAL_DOMAIN: "www.hansdesmet.be"
  SENDGRID_API_KEY: "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"
  CONTACT_TO_ADDRESS: "hello@hansdesmet.be"
  CONTACT_FROM_ADDRESS: "website@hansdesmet.be"
  CONTACT_SUBJECT: "New Message from hansdesmet.be"
