runtime: nodejs10
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always
  - url: /.*
    script: auto
    secure: always
env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  BASE_URL: "https://strak-plan.appspot.com"
  # GOOGLE_ANALYTICS_ID: "UA-157287-9"
  SENDGRID_API_KEY: "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"
  CONTACT_TO_ADDRESS: "leen@strak-plan.be"
  CONTACT_FROM_ADDRESS: "website@strak-plan.be"
  CONTACT_SUBJECT: "Nieuw bericht van Strak Plan"
